model:
  base_model: "stabilityai/stable-diffusion-xl-base-1.0"
  revision: null
  variant: null

dataset:
  data_dir: "data/processed"
  caption_column: "text"
  image_column: "image"
  max_train_samples: null
  resolution: 512
  center_crop: true
  random_flip: true

training:
  output_dir: "models/lora"
  seed: 42
  train_batch_size: 1
  num_train_epochs: 100
  max_train_steps: 1000
  gradient_accumulation_steps: 4
  gradient_checkpointing: true
  learning_rate: 1e-4
  scale_lr: false
  lr_scheduler: "constant"
  lr_warmup_steps: 0
  use_8bit_adam: false
  allow_tf32: true
  mixed_precision: "fp16"
  push_to_hub: false
  hub_model_id: null
  logging_dir: "logs"
  report_to: "tensorboard"
  local_rank: -1
  checkpointing_steps: 500
  checkpoints_total_limit: null
  resume_from_checkpoint: null
  enable_xformers_memory_efficient_attention: true
  validation_prompt: "a beautiful artwork in the style"
  num_validation_images: 4
  validation_epochs: 10

lora:
  rank: 4
  alpha: 32
  dropout: 0.0
  bias: "none"
  task_type: "DIFFUSION"